#[derive(Clone, Copy, Debug)]
pub enum Action {
    Up,
    Down,
    Enter,
    Back,
    Quit,
    EnterCommandMode,
    EnterSearchMode,
    EnterPathMode,
    EnterNormalMode,
    EnterRenameMode,
    EnterNewEntryMode,
    InputChar(char),
    InputBackspace,
    InputSubmit,
    TabComplete,
    Copy,
    Cut,
    Paste,
    Delete,
    ConfirmYes,
    ConfirmNo,
    Undo,
    Redo,
    None,
}
